export const TOGGLE_FAVORITE_CONST = "CONTENT.TOGGLE_FAVORITE";
export const SHOW_MOVIES_CONST = "CONTENT.SHOW_MOVIES";
export const SET_TOKEN_CONST = "CONTENT.SET_TOKEN";
export const SHOW_SINGLE_MOVIE_CONST = "CONTENT.SHOW_SINGLE_MOVIE";
