export const TOGGLE_FAVORITE_CONST = "CONTENT.TOGGLE_FAVORITE";
export const SHOW_MOVIES_CONST = "CONTENT.SHOW_MOVIES";
export const SET_TOKEN_CONST = "CONTENT.SET_TOKEN";
export const SHOW_SINGLE_MOVIE_CONST = "CONTENT.SHOW_SINGLE_MOVIE";

export const LOGIN_REQ = "CONTENT.LOGIN_REQ";
export const LOGIN_FAILURE = "CONTENT.LOGIN_FAILURE";
export const LOGIN_SUCESS = "CONTENT.LOGIN_SUCESS";

export const MOVIES_REQ = "CONTENT.MOVIES_REQ";
export const MOVIES_FAILURE = "CONTENT.MOVIES_FAILURE";
export const MOVIES_SUCESS = "CONTENT.MOVIES_SUCESS";
